set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property PACKAGE_PIN V17 [get_ports {A[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property PACKAGE_PIN V16 [get_ports {A[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property PACKAGE_PIN W16 [get_ports {A[2]}]

set_property PACKAGE_PIN W17 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]

set_property PACKAGE_PIN W15 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]

set_property PACKAGE_PIN V15 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]

set_property PACKAGE_PIN W14 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]

set_property PACKAGE_PIN W13 [get_ports {B[3]}]
set_property PACKAGE_PIN T17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {SEL[0]}]
set_property PACKAGE_PIN T1 [get_ports {SEL[0]}]
set_property PACKAGE_PIN U1 [get_ports {SEL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEL[1]}]
set_property PACKAGE_PIN W2 [get_ports {SEL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEL[2]}]
set_property PACKAGE_PIN R3 [get_ports {SEL[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEL[3]}]

set_property PACKAGE_PIN L1 [get_ports sign_flag]

set_property IOSTANDARD LVCMOS33 [get_ports sign_flag]
set_property IOSTANDARD LVCMOS33 [get_ports zero_flag]
set_property PACKAGE_PIN P1 [get_ports zero_flag]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports carry_flag]
set_property PACKAGE_PIN N3 [get_ports carry_flag]
set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]
set_property PACKAGE_PIN U16 [get_ports {result[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property PACKAGE_PIN E19 [get_ports {result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property PACKAGE_PIN U19 [get_ports {result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]
set_property PACKAGE_PIN W18 [get_ports {result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[0]}]
set_property PACKAGE_PIN W7 [get_ports {seg_display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[1]}]
set_property PACKAGE_PIN W6 [get_ports {seg_display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[2]}]
set_property PACKAGE_PIN U8 [get_ports {seg_display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[3]}]
set_property PACKAGE_PIN V8 [get_ports {seg_display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[4]}]
set_property PACKAGE_PIN U5 [get_ports {seg_display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[5]}]
set_property PACKAGE_PIN V5 [get_ports {seg_display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[6]}]
set_property PACKAGE_PIN U7 [get_ports {seg_display[6]}]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]
set_property -dict { PACKAGE_PIN U2    IOSTANDARD LVCMOS33 } [get_ports {an[0]}]
set_property -dict { PACKAGE_PIN U4    IOSTANDARD LVCMOS33 } [get_ports {an[1]}]
set_property -dict { PACKAGE_PIN V4    IOSTANDARD LVCMOS33 } [get_ports {an[2]}]
set_property -dict { PACKAGE_PIN W4    IOSTANDARD LVCMOS33 } [get_ports {an[3]}]
